baseurl = "https://example.com/"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Tim Mastny"
title = "Tim Mastny"
disqusshortname = ""
pluralizelisttitles = false

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2017 Timothy Mastny"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
highlightjs = true
progressively = true
align_left = false
lang = "en"
github = "example"
email = "you@example.com"
linkedin = "john-example-aa80ue8è"
twitter = "example"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
latestpostcount = 5